Parallel unit tests now allowed - eg use -j 4 in make command

diff --git a/valgrind/run_valgrind b/valgrind/run_valgrind
--- a/valgrind/run_valgrind
+++ b/valgrind/run_valgrind
@@ -4,15 +4,23 @@
 # If args are given to the command only those tests that match the args
 # will be run.
 
+flagit()
+{
+    printf "PROBLEM DETECTED HERE>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
+    print
+}
+
 check_output()
 {
     awk ' 
         BEGIN {lost = 0; found = 0}
-    	/==[0-9]*==.*lost: [1-9]/ {print; lost = 1}
-    	/==[0-9]*==.*reachable: [1-9]/ {print; lost = 1}
-    	/==[0-9]*==.*reachable: 0/ {print; found = 1}
-	/==[0-9]*== FATAL/ {print; exit(2)}
-	/[0-9]*%.* Errors: [1-9]/ {print; exit(2)}
+{print}
+    	/==[0-9]*==.*lost: [1-9]/ {flagit; lost = 1}
+    	/==[0-9]*==.*reachable: [1-9]/ {flagit; lost = 1}
+    	/==[0-9]*==.*reachable: 0/ {flagit; found = 1}
+	/==[0-9]*== FATAL/ {flagit; exit(2)}
+	/^EXITSTAT:/ {if ($2 != 0) exit($2)}
+	/[0-9]*%.* Errors: [1-9]/ {flagit; exit(2)}
 	END {
 	    if (lost) {
 		exit(1)
@@ -27,20 +35,20 @@ do_test()
 {
     echo ======== testing $1 $2 ============ >>valgrind.log
 
-    valgrind ${flags} ${cmd} ${cmd_flags} $1 $2 2>&1 | \
-	tee -a valgrind/valgrind.log | check_output >/dev/null
+    (valgrind ${flags} ${cmd} ${cmd_flags} $1 $2 2>&1; echo "EXITSTAT: $?") | \
+	tee -a valgrind.log | check_output >/dev/null
     this=$?
     if [ ${this} = 2 ]; then
-        echo "FATAL ERROR: $1 $2"
         status=${this}
+        echo "Error, FATAL: $1 $2 ${status}"
     elif [ ${this} = 3 ]; then
-        echo "UNKNOWN: $1 $2"
         status=${this}
+        echo "Unknown: $1 $2 ${status}"
     elif [ ${this} != 0 ]; then
-        echo "FAIL: $1 $2"
         status=${this}
+        echo "Error: $1 $2 ${status}"
     else
-        echo "PASS: $1 $2"
+        echo "Pass: $1 $2"
     fi
 }
 
@@ -71,7 +79,6 @@ while
   echo
 done
 
-rm -f valgrind/valgrind.log
 if [ "x$2" != "x" ]; then
     do_test $1 $2
     exit $status
